allowBuilds:
  '@parcel/watcher': set this to true or false
  browser-tabs-lock: set this to true or false
  esbuild: set this to true or false

overrides:
  workbox-build: 7.1.1
  '@babel/preset-env': 7.26.9
  '@babel/plugin-transform-modules-systemjs': 7.25.9
  '@babel/traverse': 7.26.10
  browserslist: 4.28.6
